services:
  retro-ipcam-webadmin-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: retro-ipcam-webadmin-dev
    restart: unless-stopped
    ports:
      - ${DEV_PORT:-5173}:5173
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./index.html:/usr/src/app/index.html
      - ./vite.config.ts:/usr/src/app/vite.config.ts
    command: npm run dev -- --host 0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
